"""
0f_neuron_location_matching.py
==============================
Assigns brain region labels to sorted units using histological probe tracks.
Run AFTER 0e_track_qc.py — units belonging to tracks that fail the audit
are excluded from region assignment via the track_audit_failed sentinel.

Mapping method: per-session tip-anchored with DV tissue shrinkage correction.
  peak_ch_fixed     = peak_channel_depth * DV_SCALE[mouse]            (in-vivo → fixed tissue)
  session_tip_fixed = min(insertion_depth * DV_SCALE[mouse], trace_max)
  dist              = session_tip_fixed − peak_ch_fixed                (distance from surface in fixed tissue)
Falls back to trace_max only when the recording log has no depth for the session.

DV scale factors are loaded from dv_shrinkage.csv (one row per mouse).
That CSV is generated by compute_dv_shrinkage.py from each mouse's
brainreg boundaries.tiff. Missing entries raise here — never silently default.

Inputs:
  unit_properties_with_qc.csv  — unit properties + QC pass/fail flags (output of 0d)
  dv_shrinkage.csv             — per-mouse DV shrinkage (output of compute_dv_shrinkage.py)

Outputs:
  unit_properties_with_qc_and_regions.csv  — unit properties + QC flags + region assignments
"""

import re
import shutil
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.patches import Patch

import paths as p
import constants as c

# ── Paths ──────────────────────────────────────────────────────────────────────
TRACKS_ROOT       = Path("/Volumes/T7 Shield/brain_stitching")
LOCAL_TRACKS_DIR  = p.DATA_DIR / "probe_tracks"
PLOT_DIR          = p.DATA_DIR / "location_matching"
PLOT_DIR.mkdir(parents=True, exist_ok=True)

# ── DV tissue shrinkage scale factors (fixed tissue / in-vivo) ─────────────────
# Loaded from dv_shrinkage.csv (generated by compute_dv_shrinkage.py).
# Missing entries raise — never silently default to 1.0.
_DV_SCALE_CSV = p.LOGS_DIR / "dv_shrinkage.csv"
if not _DV_SCALE_CSV.exists():
    raise FileNotFoundError(
        f"{_DV_SCALE_CSV} not found. Run `python compute_dv_shrinkage.py` first."
    )
DV_SCALE = pd.read_csv(_DV_SCALE_CSV).set_index("mouse")["scale_DV"].to_dict()


def get_dv_scale(mouse: str) -> float:
    """Return the DV shrinkage scale for a mouse, or raise with a helpful message."""
    if mouse not in DV_SCALE:
        raise KeyError(
            f"DV shrinkage missing for {mouse}. Re-run `python compute_dv_shrinkage.py` "
            f"to refresh {_DV_SCALE_CSV.name}."
        )
    return DV_SCALE[mouse]

CLEARING_PROBLEMATIC_MICE = set(
    # used to ignore mice for analysis
    # "RZ052",
    # "RZ034",
)

# ── Google Sheet — recording log ───────────────────────────────────────────────
# Used to map each unit's session to its track via (mouse, hemisphere, region).
# Track-level depth-consistency is checked in 0e; we do not re-check here.
_RECORDING_LOG_SHEET_ID = "1xpb52EO7BII-_5zIcB2HaOpZqepFcYTvBYgxA4zLyNo"
RECORDING_LOG_URL = (
    f"https://docs.google.com/spreadsheets/d/{_RECORDING_LOG_SHEET_ID}"
    "/export?format=csv&gid=0"
)


# ── Helper functions ───────────────────────────────────────────────────────────

def parse_depth(val):
    """Parse insertion depth from recording log (handles 'all', 'can't tell', etc.)."""
    if val is None or (isinstance(val, float) and np.isnan(val)):
        return None
    s = str(val).strip().lower()
    if s in ("all", "can't tell", "cant tell", ""):
        return None
    m = re.search(r"(\d+(?:\.\d+)?)", s)
    return float(m.group(1)) if m else None


def flip_hemisphere(h):
    """Recording log stores the hemisphere the probe is in; track file is on
    the opposite side (probe crosses midline and the dye tract is on that side)."""
    return "r" if str(h).strip().lower() == "l" else "l"


def build_track_name(hemisphere, region):
    return f"{flip_hemisphere(hemisphere)}_{str(region).strip().lower()}"


def copy_tracks_from_ssd():
    """Mirror per-mouse track files from SSD → local.

    For each mouse with a tracks dir on the SSD, the local tracks dir is wiped
    and re-populated. This ensures renamed/deleted tracks on the SSD don't
    leave orphan files locally.

    Mice that exist only locally (no SSD source — e.g. SSD unmounted) are left
    untouched; the function early-returns if the SSD itself isn't mounted.
    """
    if not TRACKS_ROOT.exists():
        print(f"Warning: SSD not found at {TRACKS_ROOT}. Using existing local tracks.")
        return
    LOCAL_TRACKS_DIR.mkdir(parents=True, exist_ok=True)
    n_mice = 0
    n_files = 0
    for mouse_dir in TRACKS_ROOT.iterdir():
        if not mouse_dir.is_dir():
            continue
        src_tracks = mouse_dir / "brainreg_output" / "segmentation" / "sample_space" / "tracks"
        if not src_tracks.exists():
            continue
        dst_tracks = LOCAL_TRACKS_DIR / mouse_dir.name / "brainreg_output" / "segmentation" / "sample_space" / "tracks"
        if dst_tracks.exists():
            shutil.rmtree(dst_tracks)
        dst_tracks.mkdir(parents=True, exist_ok=True)
        for src in list(src_tracks.glob("*.csv")) + list(src_tracks.glob("*.points")):
            if src.name.startswith("._"):
                continue
            shutil.copy2(src, dst_tracks / src.name)
            n_files += 1
        n_mice += 1
    print(f"Tracks refreshed from SSD: {n_files} files across {n_mice} mice → {LOCAL_TRACKS_DIR}")


def find_track_csv(mouse, track_name):
    base = LOCAL_TRACKS_DIR / mouse / "brainreg_output" / "segmentation" / "sample_space" / "tracks"
    candidate = base / f"{track_name}.csv"
    if candidate.exists():
        return candidate
    for path in base.glob("*.csv"):
        if path.name.startswith("._"):
            continue
        if track_name in path.stem:
            return path
    return None


def load_track_csv(path):
    df = pd.read_csv(path)
    df.columns = [c.strip() for c in df.columns]
    dist_col = [c for c in df.columns if "distance" in c.lower() or "dist" in c.lower()]
    if not dist_col:
        raise ValueError(f"No distance column in {path}. Columns: {list(df.columns)}")
    return df.rename(columns={dist_col[0]: "dist_um"}).sort_values("dist_um").reset_index(drop=True)


def lookup_region(track_df, dist_um):
    """Return (acronym, full_name) for a given distance along the track (fixed tissue µm)."""
    if np.isnan(dist_um):
        return ("nan_depth", "NaN depth")
    max_dist = track_df["dist_um"].max()
    min_dist = track_df["dist_um"].min()
    if dist_um < min_dist - 50:
        return ("above_surface", "Above brain surface")
    if dist_um > max_dist + 50:
        return ("below_track", "Below tracked region")
    idx = (track_df["dist_um"] - dist_um).abs().idxmin()
    row = track_df.iloc[idx]
    acronym   = str(row.get("Region acronym", row.get("region_acronym", "unknown")))
    full_name = str(row.get("Region name",    row.get("region_name",    "unknown")))
    return (acronym, full_name)


# ── 1. Load data ───────────────────────────────────────────────────────────────
print("Loading unit properties and recording log...")
up_df = pd.read_csv(p.LOGS_DIR / "unit_properties_with_qc.csv")
# Columns already renamed by 0d (mouse, id, datetime); rename only if originals still present
if "subject" in up_df.columns:
    up_df = up_df.rename(columns={"subject": "mouse", "unit": "id", "session_datetime": "datetime"})
up_df["date_only"] = pd.to_datetime(up_df["datetime"]).dt.strftime("%Y-%m-%d")

log = pd.read_csv(RECORDING_LOG_URL)
log["date_only"] = pd.to_datetime(log["date"]).dt.strftime("%Y-%m-%d")
log["depth_um"]  = log["depth"].apply(parse_depth)

print(f"  Units : {len(up_df):,} rows (all mice)")
print(f"  Log   : {len(log):,} rows")

copy_tracks_from_ssd()

# ── 1b. Load per-track audit results from 0e ──────────────────────────────────
# 0e_track_qc.py writes track_qc.csv (one row per track) with a
# `passes_audit` boolean. Tracks that fail are excluded from region assignment.
# (Tracks without units are skipped by 0e by design; the sanity check below
# only requires audit coverage for tracks that actually have units.)
_TRACK_QC_CSV = p.LOGS_DIR / "track_qc.csv"
if not _TRACK_QC_CSV.exists():
    raise FileNotFoundError(
        f"{_TRACK_QC_CSV} not found. Run `python 0e_track_qc.py` first."
    )
track_qc = pd.read_csv(_TRACK_QC_CSV)
audited_tracks = set(zip(track_qc["mouse"], track_qc["track"]))

n_failed = (~track_qc["passes_audit"]).sum()
print(f"\nTrack QC: {track_qc['passes_audit'].sum()} / {len(track_qc)} tracks pass audit")
if n_failed:
    print(f"  {n_failed} failed tracks excluded from region assignment:")
    _fail_cols = [c for c in
                  ["mouse", "track", "direction", "region_check", "depth_status",
                   "pct_outside_brain", "first_region", "last_region"]
                  if c in track_qc.columns]
    print(track_qc.loc[~track_qc["passes_audit"], _fail_cols].to_string(index=False))


# ── 2. Build session lookup ───────────────────────────────────────────────────

# Mice with tracks: scan LOCAL_TRACKS_DIR for any mouse that has at least one track CSV
mice_with_tracks = set()
if LOCAL_TRACKS_DIR.exists():
    for mouse_dir in LOCAL_TRACKS_DIR.iterdir():
        if not mouse_dir.is_dir():
            continue
        tracks_subdir = mouse_dir / "brainreg_output" / "segmentation" / "sample_space" / "tracks"
        if tracks_subdir.exists() and any(tracks_subdir.glob("*.csv")):
            mice_with_tracks.add(mouse_dir.name)

print(f"\nMice with tracks ({len(mice_with_tracks)}): {sorted(mice_with_tracks)}")

all_mice = set(log["mouse"].unique())
mice_awaiting_histology = all_mice - mice_with_tracks
print(f"Mice awaiting histology ({len(mice_awaiting_histology)}): {sorted(mice_awaiting_histology)}")

# Filter units and sessions to only mice with histology done
n_before = len(up_df)
dropped_no_histology = up_df[~up_df["mouse"].isin(mice_with_tracks)]
up_df = up_df[up_df["mouse"].isin(mice_with_tracks)].copy()
print(f"  Units (histology done): {len(up_df):,} / {n_before:,} rows")
if len(dropped_no_histology):
    print(f"  Units dropped (mouse has no histology): {len(dropped_no_histology):,}")
    print(dropped_no_histology.groupby("mouse").size().rename("n_units").to_string())

# Build session_info — used downstream to attach (region, hemisphere, track_file)
# to each unit before region lookup. Depth-consistency was checked in 0k.
session_info = log[log["mouse"].isin(mice_with_tracks)][
    ["mouse", "date_only", "insertion_number", "region", "hemisphere", "depth_um"]
].copy()
session_info["track_file"] = session_info.apply(
    lambda r: build_track_name(r["hemisphere"], r["region"]), axis=1
)

# Report units whose session isn't in the recording log at all (these become
# no_session_match downstream and are filtered out).
log_keys = set(zip(session_info["mouse"], session_info["date_only"],
                   session_info["insertion_number"].astype(int)))
unit_keys = list(zip(up_df["mouse"], up_df["date_only"],
                     up_df["insertion_number"].astype(int)))
no_log_match = up_df[[k not in log_keys for k in unit_keys]]
if len(no_log_match):
    print(f"\n  Units with no matching session in recording log:")
    print(f"  {len(no_log_match):,} units across {no_log_match['mouse'].nunique()} mice")
    print(no_log_match.groupby(["mouse", "date_only", "insertion_number"])
          .size().rename("n_units").to_string())


# ── 3. Map units to brain regions ─────────────────────────────────────────────
# Method: per-session tip-anchored with DV shrinkage correction.
#   peak_ch_fixed     = peak_channel_depth * DV_SCALE[mouse]
#   session_tip_fixed = min(insertion_depth_um * DV_SCALE[mouse], trace_max)
#   dist              = session_tip_fixed − peak_ch_fixed
# When the recording log has no depth for the session, session_tip_fixed falls
# back to trace_max. The cap protects against extrapolating past the tracked
# region (e.g. probe inserted deeper than the dye trace was recovered).
# Both dist and track dist_um are in fixed-tissue space.
# Units above the per-session surface anchor are marked above_surface.

# Per-track lookup keyed by (mouse, track) — built from track_qc + the local files.
# Holds the path, status, and pre-loaded track DataFrame for each track.
track_info = {}
for _, t in track_qc.iterrows():
    key  = (t["mouse"], t["track"])
    path = find_track_csv(t["mouse"], t["track"])
    track_info[key] = dict(
        track_path=path,
        depth_status=t.get("depth_status", ""),
        passes_audit=bool(t.get("passes_audit", False)),
    )

print("\nCaching track files...")
track_cache = {}
for info in track_info.values():
    if info["track_path"] is not None and info["track_path"] not in track_cache:
        track_cache[info["track_path"]] = load_track_csv(info["track_path"])

print("Mapping units to brain regions (per-session tip-anchored, DV-scale corrected)...")

units_merged = up_df.merge(
    session_info[["mouse", "date_only", "insertion_number",
                  "region", "hemisphere", "depth_um", "track_file"]],
    on=["mouse", "date_only", "insertion_number"],
    how="left"
)

# Sanity check: warn if any (mouse, track_file) with units is missing from
# track_qc. Those units will be excluded via the no_track_file path below; we
# don't hard-fail because the missing CSV is usually a known re-tracing gap.
needed_tracks = set(
    (m, t) for m, t in zip(units_merged["mouse"], units_merged["track_file"])
    if isinstance(t, str) and t
)
unaudited = needed_tracks - audited_tracks
if unaudited:
    print(f"\nWARNING: {len(unaudited)} (mouse, track) pairs have units but no audit row "
          f"(units will be excluded as no_track_file): {sorted(unaudited)}")

region_acronyms = []
region_names    = []
dist_along_track = []
consistency_col  = []
track_file_col   = []
depth_confidence = []

for _, row in units_merged.iterrows():
    mouse      = row["mouse"]
    track_name = row.get("track_file")

    if not isinstance(track_name, str) or not track_name:
        region_acronyms.append("no_session_match")
        region_names.append("No session match")
        dist_along_track.append(np.nan)
        consistency_col.append("no match")
        track_file_col.append(None)
        depth_confidence.append("no match")
        continue

    info = track_info.get((mouse, track_name))

    peak_d = row["peak_channel_depth"]

    if isinstance(peak_d, float) and np.isnan(peak_d):
        region_acronyms.append("unknown_depth")
        region_names.append("Depth unknown")
        dist_along_track.append(np.nan)
        consistency_col.append(info["depth_status"] if info else "no match")
        track_file_col.append(track_name)
        depth_confidence.append("unknown")
        continue

    if info is None or info["track_path"] is None:
        region_acronyms.append("no_track_file")
        region_names.append("Track file not found")
        dist_along_track.append(np.nan)
        consistency_col.append("no match" if info is None else info["depth_status"])
        track_file_col.append(track_name)
        depth_confidence.append("no track")
        continue

    if not info["passes_audit"]:
        region_acronyms.append("track_audit_failed")
        region_names.append("Track failed 0e audit")
        dist_along_track.append(np.nan)
        consistency_col.append(info["depth_status"])
        track_file_col.append(track_name)
        depth_confidence.append("track_failed")
        continue

    tdf       = track_cache[info["track_path"]]
    trace_max = tdf["dist_um"].max()

    # Convert peak_channel_depth from in-vivo to fixed tissue space
    scale         = get_dv_scale(mouse)
    peak_d_fixed  = peak_d * scale

    # Tip anchor: per-session insertion_depth (scaled to fixed tissue), capped
    # at trace_max because we can't extrapolate beyond the tracked region.
    # Falls back to trace_max when the recording log has no depth for the session.
    session_depth_um = row.get("depth_um")
    if pd.isna(session_depth_um):
        session_tip_fixed = trace_max
    else:
        session_tip_fixed = min(session_depth_um, trace_max)

    dist = session_tip_fixed - peak_d_fixed

    acronym, full_name = lookup_region(tdf, dist)
    region_acronyms.append(acronym)
    region_names.append(full_name)
    dist_along_track.append(dist)
    consistency_col.append(info["depth_status"])
    track_file_col.append(track_name)

    # Confidence tier
    if mouse in CLEARING_PROBLEMATIC_MICE:
        conf = "low"
    elif acronym == "above_surface":
        conf = "above_surface"
    elif acronym in ("below_track", "no_track_file"):
        conf = "below_track"
    else:
        conf = "ok"
    depth_confidence.append(conf)

up_df["region_acronym"]      = region_acronyms
up_df["region_name"]         = region_names
up_df["dist_along_track_um"] = dist_along_track
up_df["track_file"]          = track_file_col
up_df["depth_consistency"]   = consistency_col
up_df["depth_confidence"]    = depth_confidence

print(f"  Done mapping {len(up_df):,} units")
print(f"\n  Depth confidence breakdown:")
print(up_df["depth_confidence"].value_counts().to_string())


# ── 4. Filter to placeable units ───────────────────────────────────────────────
# Track-level gates (direction / region order / depth consistency) are all in 0e.
# Here we only drop sentinel regions left by the unit-mapping loop above:
#   - track_audit_failed: track failed any 0e gate
#   - above_surface: confirmed surface noise (amplitude/SNR worse than in-brain)
#   - below_track / no_track_file / no_session_match / unknown_depth / nan_depth:
#       unit couldn't be placed for one of these reasons.
EXCLUDE_REGIONS = {"above_surface", "below_track", "no_track_file",
                   "no_session_match", "unknown_depth", "nan_depth",
                   "track_audit_failed"}

up_df_all = up_df.copy()   # keep full df for reference

up_df = up_df[~up_df["region_acronym"].isin(EXCLUDE_REGIONS)].reset_index(drop=True)

print(f"\n  Units after filtering:")
print(f"    Total mapped              : {len(up_df_all):,}")
print(f"    track_audit_failed excluded: {(up_df_all['region_acronym']=='track_audit_failed').sum():,}")
print(f"    above_surface excluded    : {(up_df_all['region_acronym']=='above_surface').sum():,}")
print(f"    below_track excluded      : {(up_df_all['region_acronym']=='below_track').sum():,}")
print(f"    no_track_file excluded    : {(up_df_all['region_acronym']=='no_track_file').sum():,}")
print(f"    no_session_match excluded : {(up_df_all['region_acronym']=='no_session_match').sum():,}")
print(f"    unknown_depth excluded    : {(up_df_all['region_acronym']=='unknown_depth').sum():,}")
print(f"    Final clean units         : {len(up_df):,}")


# ── 5. QC plots ───────────────────────────────────────────────────────────────
# Compute probe_region here so it's available for all downstream plots
up_df["probe_region"] = up_df["track_file"].apply(
    lambda t: "str" if "_str" in str(t) else ("v1" if "_v1" in str(t) else "other")
)

# Note: 0f reports raw atlas assignments only — no waveform-based relabeling.
# Boundary recovery (ccb/GPe → CP) and other physiology-informed corrections
# live in 0h_cell_type_relabeling.py, which consumes 0g's diagnostic CSVs.

region_palette = {"str": "#2ca02c", "v1": "#9467bd", "other": "#7f7f7f"}

col = "peak_channel_depth"
fig, axes = plt.subplots(2, 2, figsize=(12, 8))
for row_axes, probe in zip(axes, ["str", "v1"]):
    subset = up_df[up_df["probe_region"] == probe][col].dropna()
    stats  = subset.describe()
    row_axes[0].hist(subset, bins=40, color=region_palette[probe],
                     edgecolor="white", linewidth=0.5, alpha=0.85)
    row_axes[0].set_xlabel("Peak channel depth (µm from probe tip, in-vivo)")
    row_axes[0].set_ylabel("Unit count")
    row_axes[0].set_title(f"{probe.upper()} — distribution of peak channel depth")
    row_axes[0].text(0.98, 0.97,
                     f"n={int(stats['count'])}\nmedian={stats['50%']:.0f}\nstd={stats['std']:.0f}",
                     transform=row_axes[0].transAxes, ha="right", va="top", fontsize=9)
    sns.ecdfplot(x=subset, ax=row_axes[1], color=region_palette[probe])
    row_axes[1].set_xlabel("Peak channel depth (µm from probe tip, in-vivo)")
    row_axes[1].set_ylabel("Cumulative fraction")
    row_axes[1].set_title(f"{probe.upper()} — CDF of peak channel depth")
plt.suptitle("Peak channel depth by probe type (STR top, V1 bottom)", fontsize=11)
plt.tight_layout()
plt.savefig(PLOT_DIR / "qc_peak_channel_depth.png", dpi=150, bbox_inches="tight")
plt.close()


# ── 6. Summary plots ──────────────────────────────────────────────────────────

# ── Plot 1: DV shrinkage per animal ───────────────────────────────────────────
shrink_pct = {m: (1 - s) * 100 for m, s in DV_SCALE.items()}
mice_sorted = sorted(shrink_pct, key=shrink_pct.get)
pcts        = [shrink_pct[m] for m in mice_sorted]
colors      = ["#d62728" if m in CLEARING_PROBLEMATIC_MICE else "#1f77b4" for m in mice_sorted]

fig, ax = plt.subplots(figsize=(6, 4))
ax.axvspan(4, 24, color="gray", alpha=0.15, label="IBL 2σ band (4–24%)")
ax.axvline(14, color="gray", linestyle="--", linewidth=1, label="IBL median (14%)")
bars = ax.barh(mice_sorted, pcts, color=colors, edgecolor="white", linewidth=0.5)
ax.set_xlabel("DV shrinkage (%)")
ax.set_title("DV tissue shrinkage per animal")

legend_elements = [Patch(facecolor="#1f77b4", label="Used")]
if CLEARING_PROBLEMATIC_MICE:
    legend_elements.append(Patch(
        facecolor="#d62728",
        label=f"Excluded ({', '.join(sorted(CLEARING_PROBLEMATIC_MICE))})"
    ))
legend_elements.append(Patch(facecolor="gray", alpha=0.3, label="IBL 2σ band (4–24%)"))
ax.legend(handles=legend_elements, fontsize=8)
ax.set_xlim(0, max(pcts) * 1.15)
for bar, val in zip(bars, pcts):
    ax.text(val + 0.3, bar.get_y() + bar.get_height() / 2,
            f"{val:.1f}%", va="center", fontsize=8)
plt.tight_layout()
plt.savefig(PLOT_DIR / "summary_shrinkage_per_animal.png", dpi=150, bbox_inches="tight")
plt.close()


# ── Plot 2: Quality metric comparison (above_surface vs in-brain) ─────────────
_METRIC_CANDIDATES = {
    "Amplitude (µV)": ["amplitude", "amplitude_uv", "mean_amplitude"],
    "SNR":            ["snr", "signal_to_noise", "amplitude_cutoff"],
    "Max drift (µm)": ["max_drift", "drift_ptp", "drift"],
    "Firing rate (Hz)":["firing_rate", "fr", "mean_firing_rate"],
}

above_s = up_df_all[up_df_all["region_acronym"] == "above_surface"]
in_brain = up_df_all[
    up_df_all["track_file"].isin(above_s["track_file"].unique()) &
    ~up_df_all["region_acronym"].isin(EXCLUDE_REGIONS)
]

found_metrics = {}
for label, candidates in _METRIC_CANDIDATES.items():
    for col in candidates:
        if col in up_df_all.columns:
            found_metrics[label] = col
            break

if found_metrics:
    n_metrics = len(found_metrics)
    fig, axes = plt.subplots(1, n_metrics, figsize=(3 * n_metrics, 4))
    if n_metrics == 1:
        axes = [axes]
    for ax, (label, col) in zip(axes, found_metrics.items()):
        vals_above  = above_s[col].dropna()
        vals_inbrain = in_brain[col].dropna()
        ax.boxplot([vals_above, vals_inbrain],
                   tick_labels=[f"above\nsurface\n(n={len(vals_above)})",
                                f"in-brain\n(n={len(vals_inbrain)})"],
                   widths=0.5, patch_artist=True,
                   boxprops=dict(facecolor="none"),
                   medianprops=dict(color="black", linewidth=2))
        ax.set_title(label, fontsize=9)
        ax.tick_params(axis="x", labelsize=8)
    plt.suptitle("Quality metrics: above-surface vs in-brain units\n(same probes)",
                 fontsize=10)
    plt.tight_layout()
    plt.savefig(PLOT_DIR / "summary_quality_above_vs_inbrain.png",
                dpi=150, bbox_inches="tight")
    plt.close()
else:
    print("  [Plot 2 skipped — no quality metric columns found in data]")


# ── Plot 3: Units per brain region ────────────────────────────────────────────
_STR_REGIONS  = {"CP", "GPe", "GPi", "STR", "PAL", "SI", "LSX", "STRd", "STRv",
                 "ACB", "OT", "CEA", "LA", "BLA", "EP", "MEA"}
_V1_REGIONS   = {"VISp", "VISp1", "VISp2/3", "VISp4", "VISp5", "VISp6a", "VISp6b",
                 "VISl", "VISrl", "VISal", "VISam", "VISpm", "VISli",
                 "VISpl", "VISpor", "VIS"}
_THAL_REGIONS = {"VAL", "LD", "LP", "CL", "RT", "VPL", "VPM", "PO", "MD", "AV",
                 "AM", "IAD", "RE", "VM", "CM", "Eth", "TH", "SGN", "MG", "LGd",
                 "LGv", "LGN", "ILM", "RN", "PIL", "SPF", "PP", "VENT", "ATN"}

def _region_color(acronym):
    a = str(acronym)
    if a in _STR_REGIONS or any(a.startswith(r) for r in ("CP", "GP", "STR", "PAL")):
        return "#2ca02c"   # green  = striatum targets
    if a in _V1_REGIONS or a.startswith("VIS"):
        return "#9467bd"   # purple = visual cortex targets
    if a in _THAL_REGIONS:
        return "#ff7f0e"   # orange = thalamus
    return "#aec7e8"       # light blue = other

legend_patches = [
    Patch(facecolor="#2ca02c", label="Striatum targets (CP, GPe, PAL…)"),
    Patch(facecolor="#9467bd", label="Visual cortex targets (VISp, VISl…)"),
    Patch(facecolor="#ff7f0e", label="Thalamus (VAL, LP, CL…)"),
    Patch(facecolor="#aec7e8", label="Other"),
]

_probe_subsets = [
    ("str", "STR probes"),
    ("v1",  "V1 probes"),
]
_counts_by_probe = {
    probe: up_df[up_df["probe_region"] == probe]["region_acronym"].value_counts()
    for probe, _ in _probe_subsets
}
max_rows = max(len(c) for c in _counts_by_probe.values()) if _counts_by_probe else 4

fig, axes = plt.subplots(1, 2, figsize=(14, max(4, max_rows * 0.35)))
for ax, (probe, probe_label) in zip(axes, _probe_subsets):
    rc = _counts_by_probe[probe]
    rc = rc[rc > 0].sort_values()
    colors = [_region_color(r) for r in rc.index]
    ax.barh(rc.index, rc.values, color=colors, edgecolor="white", linewidth=0.4)
    ax.set_xlabel("Unit count")
    ax.set_title(f"Units per region — {probe_label}  (n={rc.sum():,})")
    for i, (name, val) in enumerate(zip(rc.index, rc.values)):
        ax.text(val + 0.5, i, str(val), va="center", fontsize=7)
    ax.legend(handles=legend_patches, fontsize=8, loc="lower right")
plt.suptitle("Units per brain region by probe location", fontsize=11)
plt.tight_layout()
plt.savefig(PLOT_DIR / "summary_units_per_region.png", dpi=150, bbox_inches="tight")
plt.close()


# ── 8. Region counts and save ─────────────────────────────────────────────────
# Per-track tip region + frac_target diagnostic lives in 0e_track_qc.py
# (region_sequence, cp_in_sequence, last_region columns of track_qc.csv).
# Don't duplicate it here.

print("\nRegion counts (clean units, top 10):")
print(up_df["region_acronym"].value_counts().head(10).to_string())


# ── 9. Per-session region assignment breakdown ────────────────────────────────
# For each (mouse, date_only, probe_region), how many units land in CP vs the
# major neighbouring regions? This shows how much the CP boundary moves across
# sessions on the same probe and is the input to the §10 threshold check.
_STR_LIKE     = {"CP", "STR", "STRd", "STRv", "ACB", "OT", "PAL", "SI", "LSX"}
_GPE_LIKE     = {"GPe", "GPi", "GP"}
_FIBER_LIKE   = {"ccb", "ccs", "ccg", "fi", "dhc", "ec", "st", "cing",
                 "fp", "or", "scwm", "int", "root", "fiber_tract"}
_HPC_LIKE     = {"CA1", "CA2", "CA3", "SUB", "ProS", "DG", "HIP", "HPF"}
_THAL_LIKE    = {"VAL", "AV", "CL", "LD", "LP", "VPL", "VPM", "PO", "MD", "AM",
                 "IAD", "RE", "VM", "CM", "ATN", "ILM", "PIL", "SPF", "MG",
                 "LGd", "LGv", "PCN", "VL", "SGN", "TH", "RT"}
_CTX_PREFIXES = ("MOp", "MOs", "VIS", "SSp", "SSs", "ACA", "PL", "ILA", "ORB", "AI", "RSP")


def _region_bucket(acr):
    a = str(acr)
    if a in _STR_LIKE:
        return "CP" if a == "CP" else "STR_other"
    if a in _GPE_LIKE:
        return "GPe"
    if a in _FIBER_LIKE:
        return "fiber"
    if a in _THAL_LIKE:
        return "thal"
    if a in _HPC_LIKE:
        return "hpc"
    if any(a.startswith(px) for px in _CTX_PREFIXES):
        return "ctx"
    return "other"


up_df["_bucket"] = up_df["region_acronym"].apply(_region_bucket)

session_breakdown = (
    up_df.groupby(["mouse", "date_only", "probe_region", "_bucket"])
         .size().unstack(fill_value=0).reset_index()
)
# Ensure all bucket columns exist even if empty in this run.
for _b in ("CP", "STR_other", "GPe", "fiber", "thal", "ctx", "hpc", "other"):
    if _b not in session_breakdown.columns:
        session_breakdown[_b] = 0
session_breakdown["n_total"] = session_breakdown[
    ["CP", "STR_other", "GPe", "fiber", "thal", "ctx", "hpc", "other"]
].sum(axis=1)

# Reorder for readability.
_session_cols = ["mouse", "date_only", "probe_region", "n_total",
                 "CP", "STR_other", "GPe", "fiber", "thal", "ctx", "hpc", "other"]
session_breakdown = session_breakdown[_session_cols].sort_values(
    ["probe_region", "mouse", "date_only"]
)
up_df = up_df.drop(columns=["_bucket"])

print("\n── Per-session region assignment breakdown ──")
for probe in ("str", "v1"):
    sub = session_breakdown[session_breakdown["probe_region"] == probe]
    if not len(sub):
        continue
    print(f"\n  {probe.upper()} probe sessions ({len(sub)} (mouse, date) pairs):")
    print(sub.to_string(index=False))

session_breakdown_path = PLOT_DIR / "session_region_breakdown.csv"
session_breakdown.to_csv(session_breakdown_path, index=False)
print(f"\n  Saved → {session_breakdown_path}")


# ── 10. Session-level CP-count threshold check (≥15 units) ────────────────────
# population_decoder.py requires >15 single units per session. This is the
# downstream-facing answer to "how many usable STR sessions do you have?".
DECODER_MIN_UNITS = 15

SHORT_MICE = set(c.GROUP_DICT["s"])
LONG_MICE  = set(c.GROUP_DICT["l"])

cp_per_session = (
    up_df[(up_df["probe_region"] == "str") & (up_df["region_acronym"] == "CP")]
        .groupby(["mouse", "date_only", "insertion_number"])
        .size().rename("n_cp_units").reset_index()
)
cp_per_session["meets_threshold"] = cp_per_session["n_cp_units"] >= DECODER_MIN_UNITS
cp_per_session["bg_group"] = cp_per_session["mouse"].apply(
    lambda m: "Short BG" if m in SHORT_MICE else ("Long BG" if m in LONG_MICE else "Unassigned")
)

print("\n── Session-level CP-count threshold check ──")
print(f"  Threshold: ≥{DECODER_MIN_UNITS} CP units (STR probe) per session")
n_sessions = len(cp_per_session)
n_qualify  = int(cp_per_session["meets_threshold"].sum())
print(f"  Sessions with ≥1 CP unit  : {n_sessions}")
print(f"  Sessions meeting threshold: {n_qualify}  ({100*n_qualify/n_sessions:.0f}%)" if n_sessions else
      "  No sessions with CP units.")
for _grp in ("Short BG", "Long BG"):
    _sub = cp_per_session[cp_per_session["bg_group"] == _grp]
    if len(_sub):
        print(f"    {_grp:<9}: {int(_sub['meets_threshold'].sum())} / {len(_sub)}")


# ── 10b. Per-insertion physiological vs histological cortex–STR boundary ──────
# For each STR-probe insertion, find the depth where most units transition
# from "high FR" (cortex) to "low FR" (striatum) — that is the physiological
# cortex–STR boundary. Compare to where atlas labels switch from cortex →
# striatum (the histological boundary). A large offset is a sanity-check
# failure on the depth gate downstream uses (1500 µm in 0h).
print("\n── Per-insertion cortex–STR boundary (physiology vs histology) ──")

_BND_FR_THRESHOLD = 5.0   # Hz — units below this are likely MSNs / low-FR cells

_CTX_PREFIXES_BND = ("MOp", "MOs", "VIS", "SSp", "SSs", "ACA", "PL", "ILA", "ORB", "AI", "RSP")
_STR_REGIONS_BND  = {"CP", "STR", "STRd", "STRv", "ACB", "OT"}


def _is_ctx(r):
    r = str(r)
    return any(r.startswith(px) for px in _CTX_PREFIXES_BND)


def _is_str(r):
    return str(r) in _STR_REGIONS_BND


# Use the unfiltered (pre-EXCLUDE_REGIONS) frame so we have all sentinels;
# but boundary detection only cares about real placed units, so use up_df.
_str_units_bnd = up_df[up_df["probe_region"] == "str"].copy()
_str_units_bnd["insertion_key"] = (
    _str_units_bnd["mouse"] + "_" +
    _str_units_bnd["date_only"] + "_" +
    _str_units_bnd["insertion_number"].astype(str)
)

# Detect FR column (already on up_df from 0d).
_FR_COL_BND = next(
    (c for c in ["firing_rate", "mean_firing_rate", "fr", "spike_rate"]
     if c in _str_units_bnd.columns),
    None,
)

boundary_rows = []
if _FR_COL_BND and "peak_channel_depth" in _str_units_bnd.columns:
    for ins_key, ins_df in _str_units_bnd.groupby("insertion_key"):
        if len(ins_df) < 10:
            continue
        ins_df = ins_df.sort_values("peak_channel_depth")
        depths = ins_df["peak_channel_depth"].to_numpy()
        frs    = ins_df[_FR_COL_BND].to_numpy()
        mask   = ~np.isnan(depths) & ~np.isnan(frs)
        if mask.sum() < 10:
            continue
        depths = depths[mask]
        frs    = frs[mask]

        # Sliding window: fraction of low-FR units. First crossing of 0.5
        # ≈ cortex-STR boundary in physiology.
        win = max(3, len(depths) // 10)
        is_low = (frs < _BND_FR_THRESHOLD).astype(float)
        low_frac = np.array([
            is_low[max(0, i - win):min(len(is_low), i + win)].mean()
            for i in range(len(is_low))
        ])
        cross = np.where(low_frac > 0.5)[0]
        bnd_phys = float(depths[cross[0]]) if len(cross) else np.nan

        # Histology: first crossing of cortex-fraction below 0.5.
        is_ctx_arr = ins_df.loc[mask, "region_acronym"].apply(_is_ctx).to_numpy().astype(float)
        ctx_frac = np.array([
            is_ctx_arr[max(0, i - win):min(len(is_ctx_arr), i + win)].mean()
            for i in range(len(is_ctx_arr))
        ])
        cross_ctx = np.where(ctx_frac < 0.5)[0]
        bnd_hist = float(depths[cross_ctx[0]]) if len(cross_ctx) else np.nan

        n_ctx = int(is_ctx_arr.sum())
        n_str = int(ins_df.loc[mask, "region_acronym"].apply(_is_str).sum())
        boundary_rows.append({
            "mouse":            ins_df["mouse"].iloc[0],
            "date_only":        ins_df["date_only"].iloc[0],
            "insertion_number": int(ins_df["insertion_number"].iloc[0]),
            "n_units":          int(mask.sum()),
            "n_cortex":         n_ctx,
            "n_striatum":       n_str,
            "pct_cortex":       round(100 * n_ctx / mask.sum(), 1),
            "pct_striatum":     round(100 * n_str / mask.sum(), 1),
            "boundary_physiology_um": round(bnd_phys, 0) if not np.isnan(bnd_phys) else np.nan,
            "boundary_histology_um":  round(bnd_hist, 0) if not np.isnan(bnd_hist) else np.nan,
        })

boundary_df = pd.DataFrame(boundary_rows)
if len(boundary_df):
    boundary_df["offset_um"] = (
        boundary_df["boundary_histology_um"] - boundary_df["boundary_physiology_um"]
    )
    print(f"  Insertions analysed: {len(boundary_df)}")
    _phys = boundary_df["boundary_physiology_um"].dropna()
    _hist = boundary_df["boundary_histology_um"].dropna()
    if len(_phys):
        print(f"    Physiological boundary (FR<{_BND_FR_THRESHOLD} Hz crossover): "
              f"{_phys.mean():.0f} ± {_phys.std():.0f} µm  (n={len(_phys)})")
    if len(_hist):
        print(f"    Histological boundary  (cortex→STR label flip)        : "
              f"{_hist.mean():.0f} ± {_hist.std():.0f} µm  (n={len(_hist)})")
    if len(_phys) and len(_hist):
        _off = boundary_df["offset_um"].dropna()
        print(f"    Median offset (histology − physiology): {_off.median():.0f} µm")
        if abs(_off.median()) > 300:
            print(f"    *** WARNING: large offset — review shrinkage correction or "
                  f"the 1500 µm depth gate in 0h ***")

    boundary_path = PLOT_DIR / "boundary_phys_vs_hist.csv"
    boundary_df.to_csv(boundary_path, index=False)
    print(f"  Saved → {boundary_path}")

    # Plot: scatter of physiological vs histological boundary + offset histogram.
    _valid = boundary_df["boundary_physiology_um"].notna() & boundary_df["boundary_histology_um"].notna()
    if _valid.sum() >= 3:
        fig, axes = plt.subplots(1, 2, figsize=(13, 5))
        ax = axes[0]
        ax.scatter(boundary_df.loc[_valid, "boundary_physiology_um"],
                   boundary_df.loc[_valid, "boundary_histology_um"],
                   s=55, alpha=0.75, c="#2166AC", edgecolors="white")
        _lo = float(min(boundary_df.loc[_valid, "boundary_physiology_um"].min(),
                        boundary_df.loc[_valid, "boundary_histology_um"].min())) - 200
        _hi = float(max(boundary_df.loc[_valid, "boundary_physiology_um"].max(),
                        boundary_df.loc[_valid, "boundary_histology_um"].max())) + 200
        ax.plot([_lo, _hi], [_lo, _hi], "k--", linewidth=1, label="y = x")
        ax.set_xlim(_lo, _hi); ax.set_ylim(_lo, _hi)
        ax.set_aspect("equal")
        ax.set_xlabel("Physiological boundary (µm)\nFR-based crossover")
        ax.set_ylabel("Histological boundary (µm)\nlabel-based crossover")
        ax.set_title("Cortex–STR boundary — physiology vs histology")
        ax.grid(True, alpha=0.2); ax.legend()

        ax = axes[1]
        _off = boundary_df["offset_um"].dropna()
        if len(_off):
            ax.hist(_off, bins=15, color="#2166AC", edgecolor="white", alpha=0.75)
            ax.axvline(0, color="red", linestyle="--", label="No offset")
            ax.axvline(_off.median(), color="orange",
                       label=f"Median: {_off.median():.0f} µm")
            ax.set_xlabel("Offset (histology − physiology) (µm)")
            ax.set_ylabel("Insertion count")
            ax.set_title("Boundary offset distribution")
            ax.legend()

        fig.suptitle("Per-insertion cortex–STR boundary check", fontsize=12, fontweight="bold")
        fig.tight_layout()
        fig.savefig(PLOT_DIR / "boundary_phys_vs_hist.png", dpi=200, bbox_inches="tight")
        plt.close(fig)
        print(f"  Saved → boundary_phys_vs_hist.png")
else:
    print("  Skipped — need firing_rate + peak_channel_depth and ≥10 units / insertion.")


# ── 11. Save unit-level output ────────────────────────────────────────────────
out_path = p.LOGS_DIR / "unit_properties_with_qc_and_regions.csv"
up_df.to_csv(out_path, index=False)
print(f"\nSaved {len(up_df):,} units → {out_path}")


print(f"\nPlots saved to: {PLOT_DIR}")